### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [perlaavalos9/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are very well designed.  All of your conclusions that you can to had supporting evidence to back them up and showed a good understanding of attribution.  I loved the presentation style of displaying the query in the page along with your conclusions to give a sense of how your data was generated.  I also liked the fact that you used some visuals to display your data in a more palatable format for those reading it.  Good job here!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended. One thing that would have been great to have is inclusion of ORDER BY in some of your queries to order the data by first touch amount.  There were a few times where first touch and last touches were calculated and were displayed out of order.  It doesn't affect the conclusion at all, but can obfuscate it as it is a bit harder to read like that.  It isn't a huge deal, but something you should keep in mind in the future.

### Criteria 3: Query Formatting
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Queries adhere to at the rules of the style guide. Good work using aliases to rename the columns and using indentation to organize your subqueries, both make your queries more readable!  There are a few lines where the indentation is a bit off, but they are so few that I am not going to dock points for that.  I also suspect it may be some system related thing when uploading to Github as the rest of your queries are formatted correctly.

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated a clear understanding of the concepts of attribution and what types of applications attribution analysis has for improving business performance.  

### Overall Score: 16/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by perlaavalos9** [comment]
Thank  you for all the feedback
